# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='random_num',
            field=models.IntegerField(default=3),
        ),
    ]
